<?<?xml version="1.0"?>
<<robot name="toaster xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:property name="PI" value="3.1415926535897932" />
    <xacro:property name="wheelbase" value="0.400" />

    <xacro:property name="wheel_radius" value="0.125" />
    <xacro:property name="wheel_width" value="0.100" />
    <xacro:property name="wheel_vertical_offset" value="-0.0254" />

    <xacro:property name="dummy_inertia" value="1e-09"/>

    <material name="dark_grey"><color rgba="0.2 0.2 0.2 1.0" /></material>
    <material name="light_grey"><color rgba="0.4 0.4 0.4 1.0" /></material>
    <material name="black"><color rgba="0.15 0.15 0.15 1.0" /></material>
    <xacro:macro name="wheel" params="prefix *joint_pose">
        <link name="${prefix}_wheel_link">
            <visual>
                <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
                <geometry>
                    <mesh filename="package://toaster-description/meshes/toaster-wheel.stl"/>
                </geometry>
                <material name="black" />
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
                <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
                </geometry>
            </collision>
            <inertial>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <mass value="0.477"/>
                <inertia
                ixx="0.0013" ixy="0" ixz="0"
                iyy="0.0024" iyz="0"
                izz="0.0013"/>
            </inertial>
        </link>

        <gazebo reference="${prefix}_wheel_link">
            <material>Gazebo/DarkGrey</material>
            <selfCollide>false</selfCollide>
            <mu1 value="0.5"/>
            <mu2 value="0.5"/>
            <kp value="10000000.0" />
            <kd value="1" />
            <fdir1 value="1 0 0"/>
        </gazebo>

        <joint name="${prefix}_wheel" type="continuous">
            <parent link="chassis_link"/>
            <child link="${prefix}_wheel_link" />
            <xacro:insert_block name="joint_pose" />
            <axis xyz="0 1 0" />
        </joint>

        <transmission name="${prefix}_wheel_trans">
        <type>transmission_interface/SimpleTransmission</type>
            <joint name="${prefix}_wheel">
                <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
            </joint>
            <actuator name="${prefix}_actuator">
                <mechanicalReduction>1</mechanicalReduction>
            </actuator>
        </transmission>
    </xacro:macro>

    <xacro:wheel prefix="left">
        <origin xyz="${wheelbase/2} 0 ${wheel_vertical_offset}" rpy="0 0 0" />
    </xacro:wheel>

    <xacro:wheel prefix="right">
        <origin xyz="$-{wheelbase/2} 0 ${wheel_vertical_offset}" rpy="0 0 0" />
    </xacro:wheel>

    <link name="base_link"></link>

    <joint name="base_link_joint" type="fixed">
        <origin xyz="0 0 0" rpy="0 0 0" />
        <parent link="base_link"/>
        <child link="chassis_link" />
    </joint>

    git <link name="imu_link">
        <inertial>
        <mass value="0.001"/>
        
        <inertia ixx="${dummy_inertia}" ixy="0.0" ixz="0.0" iyy="${dummy_inertia}" iyz="0.0" izz="${dummy_inertia}"/>
        </inertial>
    </link>
    <joint name="imu_joint" type="fixed">
        <parent link="chassis_link" />
        <child link="imu_link" />
    </joint>


    <link name="chassis_link">
        <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
            <mesh filename="package://toaster-description/meshes/toaster-chassis.stl"/>
        </geometry>
            <material name="dark_grey" />
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://toaster-description/meshes/toaster-chassis.stl"/>
            </geometry>
        </collision>
        <inertial>
        <!-- Center of mass -->
        <origin xyz="0.012  0.002 0.067" rpy="0 0 0"/>
        <mass value="16.523"/>
        <!-- Moments of inertia: ( chassis without wheels ) -->
        <inertia
            ixx="0.3136" ixy="-0.0008" ixz="0.0164"
            iyy="0.3922" iyz="-0.0009"
            izz="0.4485"/>
        </inertial>
    </link>   
      <!-- Bring in simulation data for Gazebo. -->
    <xacro:include filename="$(find toaster_description)/urdf/toaster.gazebo" />

</robot>