toaster_joint_publisher:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50


toaster_velocity_controller:
  type: "diff_drive_controller/DiffDriveController"
  left_wheel: 'left_wheel'
  right_wheel: 'right_wheel'
  publish_rate: 20 
  enable_odom_tf: false

  pose_covariance_diagonal : [0.00001, 0.00001, 1000000000000.0, 1000000000000.0, 1000000000000.0, 0.001]
  twist_covariance_diagonal: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

  # Wheel separation and radius multipliers
  wheel_separation_multiplier: 1.0 # default: 1.0
  wheel_radius_multiplier    : 1.0 # default: 1.0

  # Velocity commands timeout [s], default 0.5
  cmd_vel_timeout: 0.2


  linear:
    x:
      has_velocity_limits    : true
      max_velocity           : 2.0   # m/s
      has_acceleration_limits: true
      max_acceleration       : 20.0   # m/s^2
  angular:
    z:
      has_velocity_limits    : true
      max_velocity           : 4.0   # rad/s
      has_acceleration_limits: true
      max_acceleration       : 25.0   # rad/s^2
