#http://docs.ros.org/en/lunar/api/robot_localization/html/state_estimation_nodes.html#:~:text=false%5D%3C/rosparam%3E-,The%20order%20of%20the%20boolean%20values%20are,.,-Note%20The%20specification

frequency: 50
debug: false
debug_out_file: /home/ubuntu/ekf_debug.txt
two_d_mode: true
twist0: /roboclaw/twist
twist0_config: [false, false, false,
               false, false, false,
               true, true, false,
               false, false, true,
               false, false, false]
twist0_differential: false

imu0: /vectornav/IMU
imu0_config: [false, false, false,
              true, true, false,
              false, false, false,
              true, true, true,
              true, false, false]
imu0_differential: false
odom_frame: odom
base_link_frame: base_link
world_frame: odom
map_frame: map
predict_to_current_time: true
