topics: 
  - 
    name: interactive_marker
    priority: 8
    timeout: 0.5
    topic: twist_marker_server/cmd_vel
  - 
    name: external
    priority: 1
    timeout: 0.5
    topic: cmd_vel
locks: 
  - 
    name: e_stop
    priority: 255
    timeout: 0.0
    topic: e_stop