topics: 
  - 
    name: interactive_marker
    priority: 8
    timeout: 0.5
    topic: twist_marker_server/cmd_vel
  - 
    name: ds4
    priority: 10
    timeout: 0.1
    topic: ds4/cmd_vel
    
    name: external
    priority: 9
    timeout: 0.5
    topic: cmd_vel
locks: 
  - 
    name: e_stop
    priority: 255
    timeout: 0.0
    topic: e_stop